# Site
name: 'SIAM Student Chapter, SDSU'
description: 'Society for Industrial and Applied Mathematicians Student Chapter at San Diego State University'
logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
# baseurl: "/"
# baseurl: "https://siamscsdsu.github.io"
email: 'siamscsdsu@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
# Team names, titles and social links
people:
- name: Ashley Schwartz
  pic: 1
  position: President
  email: avschwartz@sdsu.edu
  linkedin: https://www.linkedin.com/in/ashleyvsch/

- name: Hayden Frye
  pic: hayden
  position: Vice President
  email: hfrye@sdsu.edu
  linkedin: 

- name: Christine Cho
  pic: christine
  position: Treasurer
  email: ccho0148@sdsu.edu
  linkedin: 

# - name: Delaney Farrell
#   pic: missing
#   position: Secretary
#   email: 
#   linkedin: 

- name: Audrey Oliver
  pic: audrey
  position: Special Events Planner
  email: akoliver@sdsu.edu
  linkedin: 

- name: Dr. Jose Castillo
  pic: jose
  position: Faculty Advisor
  email: jcastillo@sdsu.edu
  linkedin: 

 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]