# Site
name: 'SIAM Student Chapter at SDSU'
description: 'Society for Industrial and Applied Mathematicians Student Chapter at San Diego State University'
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
# baseurl: "/"
# baseurl: "https://siamscsdsu.github.io"
email: 'siamscsdsu@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
# Team names, titles and social links
people:
- name: Daisy Ulloa
  pic: daisy1
  position: President
  email: dulloa3712@sdsu.edu
  linkedin: https://www.linkedin.com/in/daisyu/

- name: Christine Cho
  pic: christine
  position: Vice President
  email: ccho0148@sdsu.edu
  linkedin: https://www.linkedin.com/in/christine-s-cho/

- name: Juan S. Carrillo!!!
  pic: seb
  position: Treasurer
  email: jcarrillo5698@sdsu.edu
  linkedin: https://www.linkedin.com/in/juan-s-carrillo/

- name: Mingshuo Liu
  pic: mingshuo
  position: Secretary
  email: mliu4036@sdsu.edu
  linkedin: https://www.linkedin.com/in/mingshuo-liu-4210511b8/

- name: Gianni Pucillo
  pic: gianni
  position: Public Relations
  email: gpucillo4016@sdsu.edu
  linkedin: https://www.linkedin.com/in/gianni-pucillo-451a27294/

- name: Dr. Jose Castillo
  pic: jose
  position: Faculty Advisor
  email: jcastillo@sdsu.edu
  linkedin: https://www.linkedin.com/in/jose-castillo-901a481/

 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]