# Site
name: 'SIAM Student Chapter at SDSU'
description: 'Society for Industrial and Applied Mathematicians Student Chapter at San Diego State University'
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
# baseurl: "/"
# baseurl: "https://siamscsdsu.github.io"
email: 'siamscsdsu@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
# Team names, titles and social links
people:
- name: Daisy Ulloa
  pic: daisy
  position: President
  email: avschwartz@sdsu.edu
  linkedin: https://www.linkedin.com/in/ashleyvsch/

- name: Christine Cho
  pic: hayden
  position: Vice President
  email: hfrye1604@sdsu.edu
  linkedin: https://www.linkedin.com/in/hayden-frye-940b0b176/

- name: Juan S. Carrillo
  pic: audrey
  position: Treasurer
  email: akoliver@sdsu.edu
  linkedin: https://www.linkedin.com/in/audrey-oliver/

- name: Christian Quiroz
  pic: christian
  position: Secretary
  email: cquiroz8279@gmail.com
  linkedin: https://www.linkedin.com/in/christian-quiroz-58827b212

- name: Timmy Liang
  pic: missing
  position: Public Relations
  email: tliang7106@sdsu.edu
  linkedin: https://www.linkedin.com/in/timmy-l-130a29149/

- name: Dr. Jose Castillo
  pic: jose
  position: Faculty Advisor
  email: jcastillo@sdsu.edu
  linkedin: https://www.linkedin.com/in/jose-castillo-901a481/

 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]